/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    openDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_openDevice
  (JNIEnv *, jclass);

/*
 * Class:     HelloJNI
 * Method:    getCapabilities
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_getCapabilities
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
