/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
#undef HelloJNI_CAPABILITY_OFFSET
#define HelloJNI_CAPABILITY_OFFSET 16L
/*
 * Class:     HelloJNI
 * Method:    openDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_openDevice
  (JNIEnv *, jclass);

/*
 * Class:     HelloJNI
 * Method:    closeDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_closeDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     HelloJNI
 * Method:    getDeviceCapabilities
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_HelloJNI_getDeviceCapabilities
  (JNIEnv *, jclass, jint);

/*
 * Class:     HelloJNI
 * Method:    getDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HelloJNI_getDeviceName
  (JNIEnv *, jclass, jint);

/*
 * Class:     HelloJNI
 * Method:    setAutocenter
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_setAutocenter
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     HelloJNI
 * Method:    playEffect
 * Signature: (ILHelloJNI/FFEffect;)S
 */
JNIEXPORT jshort JNICALL Java_HelloJNI_playEffect
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     HelloJNI
 * Method:    removeEffect
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_HelloJNI_removeEffect
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
