/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeDevice */

#ifndef _Included_NativeDevice
#define _Included_NativeDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeDevice
 * Method:    nativeOpenDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_NativeDevice_nativeOpenDevice
  (JNIEnv *, jclass);

/*
 * Class:     NativeDevice
 * Method:    nativeCloseDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeDevice_nativeCloseDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     NativeDevice
 * Method:    nativeGetDeviceCapabilities
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_NativeDevice_nativeGetDeviceCapabilities
  (JNIEnv *, jclass, jint);

/*
 * Class:     NativeDevice
 * Method:    nativeGetDeviceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NativeDevice_nativeGetDeviceName
  (JNIEnv *, jclass, jint);

/*
 * Class:     NativeDevice
 * Method:    nativeSetAutocenter
 * Signature: (ID)I
 */
JNIEXPORT jint JNICALL Java_NativeDevice_nativeSetAutocenter
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     NativeDevice
 * Method:    nativePlayEffect
 * Signature: (ILFFEffect;)S
 */
JNIEXPORT jshort JNICALL Java_NativeDevice_nativePlayEffect
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     NativeDevice
 * Method:    nativeRemoveEffect
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeDevice_nativeRemoveEffect
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
